- name: Ensure Keycloak is started
  service:
    name: keycloak
    state: started
- name: create reverse-proxy-config.cli command file
  template:
    src: reverse-proxy-config.cli.j2
    dest: "{{ keycloak_config_dir }}/reverse-proxy-config.cli"
    owner: root
    group: root
    mode: 0600
- name: apply keycloak proxy configuration
  command:
  args:
    argv:
    - "{{ keycloak_jboss_home }}/bin/jboss-cli.sh"
    - --connect
    - --timeout={{ keycloak_jboss_config_connect_timeout }}
    - --command-timeout={{ keycloak_jboss_config_command_timeout }}
    - --file={{ keycloak_config_dir }}/reverse-proxy-config.cli
  tags:
  - skip_ansible_lint
- name: clean up jboss-cli-sh command file
  file:
    path: "{{ keycloak_config_dir }}/reverse-proxy-config.cli"
    state: absent